#!/bin/sh

# Set these paths appropriately

BIN=./bin
CMD=./cmd
LIB=./lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/greek-mwls.pl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/greek-abbreviations-utf8
PARFILE=${LIB}/greek-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

